name: Continuous Integration Github Action

on:
  push:
  pull_request:
jobs:
  run-static-codebase-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run formatter
        run: npm run format
      - name: Run type-check
        run: npm run type-check
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run unit & integration tests
        run: npm run test
      - name: Run e2e tests
        run: npm run e2e-test
